//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelatorioExcel.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MHZPRESTADORESEntities : DbContext
    {
        public MHZPRESTADORESEntities()
            : base("name=MHZPRESTADORESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<COLABORADORES> COLABORADORES { get; set; }
        public virtual DbSet<CONTRATOes> CONTRATOes { get; set; }
        public virtual DbSet<CREDENCIAMENTOS> CREDENCIAMENTOS { get; set; }
        public virtual DbSet<ESPECIALIDADE_EXAMES> ESPECIALIDADE_EXAMES { get; set; }
        public virtual DbSet<METAS> METAS { get; set; }
    }
}
