//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelatorioExcel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLABORADORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLABORADORES()
        {
            this.CREDENCIAMENTOS = new HashSet<CREDENCIAMENTOS>();
        }
    
        public int ID_COLABORADOR { get; set; }
        public string NOME_FANTASIA { get; set; }
        public string RAZAO_SOCIAL { get; set; }
        public string CPF_CNPJ { get; set; }
        public string DDD { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string ESTADO { get; set; }
        public string UF { get; set; }
        public string CIDADE { get; set; }
        public string CEP { get; set; }
        public string TIPO_LOGRADOURO { get; set; }
        public string LOGRADOURO { get; set; }
        public string Numero { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public string ESPECIALIDADE { get; set; }
        public string CLIENTE { get; set; }
        public string TIPO { get; set; }
        public string EMAIL { get; set; }
        public string CONTATO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREDENCIAMENTOS> CREDENCIAMENTOS { get; set; }
    }
}
