//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelatorioExcel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIALIDADE_EXAMES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESPECIALIDADE_EXAMES()
        {
            this.CREDENCIAMENTOS = new HashSet<CREDENCIAMENTOS>();
            this.METAS = new HashSet<METAS>();
        }
    
        public int ID_ESPECIALIDADE { get; set; }
        public string NOME_ESPECIALIDADE { get; set; }
        public int TIPO_EXAM_ESP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREDENCIAMENTOS> CREDENCIAMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<METAS> METAS { get; set; }
    }
}
